

very-so-much: DI HolidaysSeasonsAreHere Awesomeness


server:
  port: ${PORT:8084}


eureka:
  client:
    serviceUrl:
      # defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://192.168.150.100:8761}/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
